import type { Metadata } from 'next';
import {
    JetBrains_Mono,
    Fira_Code,
    IBM_Plex_Mono,
    Space_Mono,
} from 'next/font/google';
import './ui/globals.css';
import Header from './ui/layout/header';
import Footer from './ui/layout/footer';

const jetbrainsMono = JetBrains_Mono({
    subsets: ['latin'],
    variable: '--ff-jetbrains-mono',
});
const firaCode = Fira_Code({
    subsets: ['latin'],
    variable: '--ff-fira-code',
});
const ibmPlexMono = IBM_Plex_Mono({
    subsets: ['latin'],
    weight: ['400', '500', '600'],
    variable: '--ff-ibm-plex-mono',
});
const spaceMono = Space_Mono({
    subsets: ['latin'],
    weight: ['400', '700'],
    variable: '--ff-space-mono',
});

const fontVars = [
    jetbrainsMono.variable,
    firaCode.variable,
    ibmPlexMono.variable,
    spaceMono.variable,
].join(' ');

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="de"
            data-accent="amber"
            data-font="jetbrains-mono"
            className={`${fontVars} h-full antialiased`}
        >
            <body className="flex flex-col">
                <Header />
                <main className="min-h-screen max-w-6xl mx-auto pt-36">
                    {children}
                </main>
                <div className="w-full max-w-6xl mx-auto">
                    <Footer />
                </div>
            </body>
        </html>
    );
}
